export const APP_DATA = {
  name: "Logo.it",
  version: "0.0.1",
  description: "Logoit is a logo maker tool",
  author: "Jayakrishnan M",
  website: "https://www.ghostkode.com/",
  keywords: [
    "logo",
    "design",
    "tool",
    "maker",
    "branding",
    "brand",
    "identity",
    "logotype",
    "logomark",
    "logos",
    "logos design",
    "logos maker",
    "logos creator",
    "logos generator",
    "logos online",
    "logos free",
    "logos download",
    "logos software",
    "logos app",
    "logos ideas",
    "logos inspiration",
    "logos for business",
    "logos for free",
    "logos for download",
    "logos for software",
  ],
  twitter: "@ghostkoder",
};

export const LOGO_ID = "logo-it-logo";
